package vn.gmostore.basic.model;

// default package
// Generated Oct 27, 2013 8:20:49 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.search.annotations.Indexed;

/**
 * ListType generated by hbm2java
 */
@Entity
@Table(name = "list_type", catalog = "gmostore_db")
@Indexed(index = "ListTypes")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class ListType extends AbstractDomain<Integer> {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private String name;
    private String imageUrl;
    private String orderType;
    private String position;
    private Boolean manual;
    private long createDate;
    private Long updateDate;
    private Long deleteDate;
    @JsonIgnore
    private Set<ListTypeHasProduct> listTypeHasProducts = new HashSet<ListTypeHasProduct>(0);

    public ListType() {
    }

    public ListType(String name) {
        this.name = name;
    }

    public ListType(String name, String imageUrl, String orderType, String position, Boolean manual, long createDate, Long updateDate, Long deleteDate,
            Set<ListTypeHasProduct> listTypeHasProducts) {
        this.name = name;
        this.imageUrl = imageUrl;
        this.orderType = orderType;
        this.position = position;
        this.manual = manual;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.deleteDate = deleteDate;
        this.listTypeHasProducts = listTypeHasProducts;
    }

    @Override
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "image_url")
    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @Column(name = "order_type", length = 20)
    public String getOrderType() {
        return this.orderType;
    }

    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    @Column(name = "position", length = 20)
    public String getPosition() {
        return this.position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    @Column(name = "manual")
    public Boolean getManual() {
        return this.manual;
    }

    public void setManual(Boolean manual) {
        this.manual = manual;
    }

    @Column(name = "create_date")
    public long getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(long createDate) {
        this.createDate = createDate;
    }

    @Column(name = "update_date")
    public Long getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Long updateDate) {
        this.updateDate = updateDate;
    }

    @Column(name = "delete_date")
    public Long getDeleteDate() {
        return this.deleteDate;
    }

    public void setDeleteDate(Long deleteDate) {
        this.deleteDate = deleteDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "listType")
    public Set<ListTypeHasProduct> getListTypeHasProducts() {
        return this.listTypeHasProducts;
    }

    public void setListTypeHasProducts(Set<ListTypeHasProduct> listTypeHasProducts) {
        this.listTypeHasProducts = listTypeHasProducts;
    }

}
