package vn.gmostore.basic.model;

// default package
// Generated Oct 27, 2013 8:20:49 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * ListTypeHasProduct generated by hbm2java
 */
@Entity
@Table(name = "list_type_has_product", catalog = "gmostore_db")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class ListTypeHasProduct extends AbstractDomain<ListTypeHasProductId> {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private ListTypeHasProductId id;
    private Product product;
    private ListType listType;

    public ListTypeHasProduct() {
    }

    public ListTypeHasProduct(ListTypeHasProductId id, Product product, ListType listType) {
        this.id = id;
        this.product = product;
        this.listType = listType;
    }

    @Override
    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "listTypeId", column = @Column(name = "list_type_id", nullable = false)),
            @AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)) })
    public ListTypeHasProductId getId() {
        return this.id;
    }

    @Override
    public void setId(ListTypeHasProductId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "list_type_id", nullable = false, insertable = false, updatable = false)
    public ListType getListType() {
        return this.listType;
    }

    public void setListType(ListType listType) {
        this.listType = listType;
    }

}
