package vn.gmostore.basic.model;

// default package
// Generated Oct 27, 2013 8:20:49 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "promotion", catalog = "gmostore_db")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Promotion extends AbstractDomain<Integer> {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private Product product;
    private String name;
    private String description;
    private int diamond;
    private int gold;
    private int point;
    private Long startDate;
    private Long endDate;
    private long createDate;
    private Long updateDate;
    private Long deleteDate;
    private Set<HistoryTransaction> historyTransactions = new HashSet<HistoryTransaction>(0);

    public Promotion() {
    }

    public Promotion(Product product, String name, int diamond, int gold, int point) {
        this.product = product;
        this.name = name;
        this.diamond = diamond;
        this.gold = gold;
        this.point = point;
    }

    public Promotion(Product product, String name, String description, int diamond, int gold, int point, Long startDate, Long endDate, Long updateDate,
            Long deleteDate, Set<HistoryTransaction> historyTransactions) {
        this.product = product;
        this.name = name;
        this.description = description;
        this.diamond = diamond;
        this.gold = gold;
        this.point = point;
        this.startDate = startDate;
        this.endDate = endDate;
        this.updateDate = updateDate;
        this.deleteDate = deleteDate;
        this.historyTransactions = historyTransactions;
    }

    @Override
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    @Column(name = "name", nullable = false, length = 20)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "diamond", nullable = false)
    public int getDiamond() {
        return this.diamond;
    }

    public void setDiamond(int diamond) {
        this.diamond = diamond;
    }

    @Column(name = "gold", nullable = false)
    public int getGold() {
        return this.gold;
    }

    public void setGold(int gold) {
        this.gold = gold;
    }

    @Column(name = "point", nullable = false)
    public int getPoint() {
        return this.point;
    }

    public void setPoint(int point) {
        this.point = point;
    }

    @Column(name = "start_date")
    public Long getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Long startDate) {
        this.startDate = startDate;
    }

    @Column(name = "end_date")
    public Long getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Long endDate) {
        this.endDate = endDate;
    }

    @Column(name = "create_date")
    public long getCreateDate() {
        return createDate;
    }

    public void setCreateDate(long createDate) {
        this.createDate = createDate;
    }

    @Column(name = "update_date")
    public Long getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Long updateDate) {
        this.updateDate = updateDate;
    }

    @Column(name = "delete_date")
    public Long getDeleteDate() {
        return this.deleteDate;
    }

    public void setDeleteDate(Long deleteDate) {
        this.deleteDate = deleteDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
    public Set<HistoryTransaction> getHistoryTransactions() {
        return this.historyTransactions;
    }

    public void setHistoryTransactions(Set<HistoryTransaction> historyTransactions) {
        this.historyTransactions = historyTransactions;
    }

}
