package vn.gmostore.basic.model;

// default package
// Generated Oct 27, 2013 8:20:49 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Sns generated by hbm2java
 */
@Entity
@Table(name = "sns", catalog = "gmostore_db")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Sns extends AbstractDomain<Integer> {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private User user;
    private String snsName;
    private byte snsType;
    private long createDate;
    private Long updateDate;
    private Long deleteDate;
    private Set<SnsFriendList> snsFriendLists = new HashSet<SnsFriendList>(0);

    public Sns() {
    }

    public Sns(User user, String snsName, byte snsType, long createDate) {
        this.user = user;
        this.snsName = snsName;
        this.snsType = snsType;
        this.createDate = createDate;
    }

    public Sns(User user, String snsName, byte snsType, long createDate, Long updateDate, Long deleteDate, Set<SnsFriendList> snsFriendLists) {
        this.user = user;
        this.snsName = snsName;
        this.snsType = snsType;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.deleteDate = deleteDate;
        this.snsFriendLists = snsFriendLists;
    }

    @Override
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "sns_name", nullable = false)
    public String getSnsName() {
        return this.snsName;
    }

    public void setSnsName(String snsName) {
        this.snsName = snsName;
    }

    @Column(name = "sns_type", nullable = false)
    public byte getSnsType() {
        return this.snsType;
    }

    public void setSnsType(byte snsType) {
        this.snsType = snsType;
    }

    @Column(name = "create_date", nullable = false)
    public long getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(long createDate) {
        this.createDate = createDate;
    }

    @Column(name = "update_date")
    public Long getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Long updateDate) {
        this.updateDate = updateDate;
    }

    @Column(name = "delete_date")
    public Long getDeleteDate() {
        return this.deleteDate;
    }

    public void setDeleteDate(Long deleteDate) {
        this.deleteDate = deleteDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sns")
    public Set<SnsFriendList> getSnsFriendLists() {
        return this.snsFriendLists;
    }

    public void setSnsFriendLists(Set<SnsFriendList> snsFriendLists) {
        this.snsFriendLists = snsFriendLists;
    }

}
