package vn.gmostore.basic.model;

// default package
// Generated Oct 27, 2013 8:20:49 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.search.annotations.Indexed;

/**
 * UserDevice generated by hbm2java
 */
@Entity
@Table(name = "user_device", catalog = "gmostore_db")
@Indexed(index = "UserDevices")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class UserDevice extends AbstractDomain<Integer> {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private User user;
    private DeviceInfo deviceInfo;
    private Long loginDate;

    public UserDevice() {
    }

    public UserDevice(User user, DeviceInfo deviceInfo) {
        this.user = user;
        this.deviceInfo = deviceInfo;
    }

    public UserDevice(User user, DeviceInfo deviceInfo, Long loginDate) {
        this.user = user;
        this.deviceInfo = deviceInfo;
        this.loginDate = loginDate;
    }

    @Override
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "device_info_id", nullable = false)
    public DeviceInfo getDeviceInfo() {
        return this.deviceInfo;
    }

    public void setDeviceInfo(DeviceInfo deviceInfo) {
        this.deviceInfo = deviceInfo;
    }

    @Column(name = "login_date")
    public Long getLoginDate() {
        return this.loginDate;
    }

    public void setLoginDate(Long loginDate) {
        this.loginDate = loginDate;
    }

}
